version: '3.8'
services:
  stepcraft_web:
    build: .
    container_name: stepcraft_web
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
        - ../.env
    environment:
      - DATABASE_URL=sqlite:///./stepcraft_web.sqlite3
      - STEPCRAFT_WEB_SECRET=${STEPCRAFT_WEB_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    volumes:
      - ./stepcraft_web.sqlite3:/app/stepcraft_web.sqlite3
